# Generated by Django 6.0.7 on 2026-08-10 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='callable',
            new_name='category',
        ),
    ]
